language: node_js
node_js:
  - 10

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - ~/.npm
    - ~/.cache

branches:
  only:
    - master

install:
  - set -e
  - npm ci

script:
  - set -e
  - npm run lint:js --quiet
  - npm run serve &
  - npm run test:ci
